### ISSUE TITLE
Fix Resolution [Responsive Layout]

### ISSUE THREAD

**Issue by rishudixit** [rishudixit/xos#1]
The text should not be hidden like this. Result window should be wide enough to display results properly.

![image](https://user-images.githubusercontent.com/108553089/195898819-7637f775-db59-4328-8243-0a77bb1f06cb.png)

**Comment by siddhantdixit** [comment]
Can you assign this issue to me?

**Comment by rishudixit** [comment]
okay! @siddhantdixit
