### ISSUE TITLE
New Icon for XOS Game

### ISSUE THREAD

**Issue by rishudixit** [rishudixit/xos#2]
Current XOS Game have default python icon. It would be better to get new Tic Tac Toe like icon for our game.

![image](https://user-images.githubusercontent.com/108553089/195899643-ecf1d6f7-00f7-4e6a-a289-8a85c7a69ec1.png)

**Comment by siddhantdixit** [comment]
Can I work on this issue?

**Comment by rishudixit** [comment]
You can work on this. @siddhantdixit
